title: RC Mixtape
url: https://mixtape.recurse.com
plugins:
  - jekyll-seo-tag
exclude: [ "Gemfile*" ]
include: [ "_redirects" ]
collections:
  mixtapes:   { "output": true, "permalink": "/:path" }
defaults:
  -
    scope:  { "path": "", "type": "mixtapes" }
    values: { "layout": "mixtape" }
